### ISSUE TITLE
pip install failed

### ISSUE THREAD

**Issue by Leo-LiHao** [bauwenst/TkTkT#1]
Hi, I tried to install the package by `pip install "tktkt[github] @ git+https://github.com/bauwenst/TkTkT.git"` but encountered the following error:

> INFO: pip is looking at multiple versions of bpe-knockout[github] to determine which version is compatible with other requirements. This could take a while.
> ERROR: Cannot install bpe-knockout[github]==2024.4.1, tktkt 2024.6.1 (from git+https://github.com/bauwenst/TkTkT.git) and tktkt[github]==2024.6.1 because these package versions have conflicting dependencies.
> 
> The conflict is caused by:
>     The user requested tktkt 2024.6.1 (from git+https://github.com/bauwenst/TkTkT.git)
>     tktkt[github] 2024.6.1 depends on tktkt 2024.6.1 (from git+https://github.com/bauwenst/TkTkT.git)
>     bpe-knockout[github] 2024.4.1 depends on tktkt 2024.6.1 (from git+https://github.com/bauwenst/TkTkT)
> 
> To fix this you could try to:
> 1. loosen the range of package versions you've specified
> 2. remove package versions to allow pip attempt to solve the dependency conflict
> 
> ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by bauwenst** [comment]
As far as I can see, the reason must be the `.git` at the end of the `pip install` command. What's happening is that it's installing `TkTkT.git`, finds that it has to install `BPE-knockout`, and then finds that it has to install `TkTkT` without the `.git`, under the same package name.

To fix this, run `pip install "tktkt[github] @ git+https://github.com/bauwenst/TkTkT"` instead.

It turns out that adding `.git` to the end of a URL is only done when there are no files in the repo yet. I'm going to delete `.git` from all my READMEs in that case. Thanks for raising the issue!
